//
// Created by otrush on 1/15/2026.
//

#ifndef SHIFT_TEXTUREMANAGER_HPP
#define SHIFT_TEXTUREMANAGER_HPP

#include <cstdint>
#include <memory>
#include <string>
#include <unordered_map>

#include "Loaders/ModelLoader/IModelLoader.hpp"
#include "Loaders/TextureLoader/ITextureLoader.hpp"

#include "Graphics/RHI/RHI.hpp"
#include "GenerationalPool.hpp"
#include "GlobalResourceSet.hpp"

namespace Shift::Graphics {

    //! Opaque, generation-checked reference to a bindless texture. slotIdx IS the index the shader
    //! samples in the bindless array
    using TextureHandle = GenerationalPool<Texture>::Handle;

    class TextureManager {
    public:
        //! Full mip chain is generated by default
        static constexpr uint32_t FULL_MIP_CHAIN = UINT32_MAX;

        //! Color space is part of the cache key cuz different colot space chnages how vk image is created, and this is not a fixed argument
        //! I may load Megamind.png as a normal map AND basecolor, yknow? (I mean i should not, but there can be cases)
        //! Another good usecase is using non-black/white placeholder 1x1 textures in place of linear and srgb textures as it will skew the,
        //! Miplevels are also here kiinda for the same reason lol
        struct CacheKey {
            std::string path;
            ETextureColorSpace colorSpace = ETextureColorSpace::SRGB;
            uint32_t mipLevels = FULL_MIP_CHAIN;

            [[nodiscard]] bool operator==(const CacheKey& other) const = default;
        };

        struct CacheKeyHash {
            [[nodiscard]] size_t operator()(const CacheKey& key) const;
        };

        TextureManager(ITextureLoader* loader, RenderBackend* rhi, GlobalResourceSet* globalSet, RenderContextEncoder* encode);

        [[nodiscard]] TextureHandle GetOrLoadTexture(const std::string& path, RenderContextEncoder* encode,
                                                     ETextureColorSpace colorSpace = ETextureColorSpace::SRGB,
                                                     uint32_t mipLevels = FULL_MIP_CHAIN);

        void UnloadTexture(const TextureHandle& texHandle);

        [[nodiscard]] bool IsValid(const TextureHandle& handle) const;

        [[nodiscard]] ETextureFormat GetFormat(const TextureHandle& handle) const;

        [[nodiscard]] ETextureFormat GetFormatOfSlot(uint32_t slotIdx);

        [[nodiscard]] uint32_t GetMipCount(const TextureHandle& handle) const;

        [[nodiscard]] uint32_t GetMipCountOfSlot(uint32_t slotIdx);

        [[nodiscard]] uint32_t GetLoadedCount() const { return static_cast<uint32_t>(m_cache.size()); }

        //! The permanently-resident 1x1 fallback at slot 0
        //! Never unloadable apart from destruction
        [[nodiscard]] TextureHandle GetPlaceholderHandle() const { return m_placeholder; }

        //! TODO [Feature] Implement a staging buffer pool so that this is not needed
        void FreeStagingBuffers();

        void UploadTexturesToGPU(RenderContextEncoder* encoder);

        ///! ================ Mid-run uploads ====================

        //! Book a texture slot and add the load to pending for the submit pending uploads that runs once per frame
        [[nodiscard]] TextureHandle LoadTextureDeferred(const std::string& path,
                                                        ETextureColorSpace colorSpace = ETextureColorSpace::SRGB,
                                                        uint32_t mipLevels = FULL_MIP_CHAIN);

        //! Record and submit every deferred upload queued so far on the transfer queue.
        //! No-op when nothing is pending. Must run before the frame's graphics recording begins
        [[nodiscard]] bool SubmitPendingUploads();

        //! Point the bindless slots of the last submitted uploads at their real images.
        //! Must run after RHI::FlushPendingAcquires as we switch queues (potentially I guess)
        //! Muips are also built here!
        void RegisterSubmittedUploads(RenderContextEncoder* encoder);

        ~TextureManager();
    private:
        //! ============ The texture cache ============

        //! The handle already loaded for this key, or a invalid handle
        [[nodiscard]] TextureHandle FindInCache(const CacheKey& key) const;

        void StoreInCache(const CacheKey& key, TextureHandle handle);

        //! Just get the Raw data from an image. Colorspace decides srgb or UNORM
        [[nodiscard]] std::optional<RawTextureData> LoadRawData(const std::string& path, ETextureColorSpace colorSpace);

        //! Create the GPU texture object sized/formatted for this raw data. Records nothing
        [[nodiscard]] Texture* CreateTextureForRaw(const std::string& path, const RawTextureData& raw, uint32_t requestedMipLevels);

        //! Record transfer-queue upload commands for one texture: staging fill, copy and the
        //! release half of the handoff to graphics. Returns the staging buffer
        [[nodiscard]] Buffer* RecordUploadCommands(Texture& texture, const RawTextureData& raw, RenderContextEncoder& encoder);

        Texture* LoadAndCreateTexture(const std::string & path, RenderContextEncoder* encode, ETextureColorSpace colorSpace, uint32_t mipLevels);

        //! The finalize function both for deferred and init uploads
        void FinalizeUpload(RenderContextEncoder* encoder, uint32_t slotIdx, Texture* texture);

        void UploadToGPU(uint32_t slotIdx, Texture * texture);

        void ClearTexture(uint32_t slotIdx);

        GenerationalPool<Texture> m_pool;
        //! Texture + colorspace -> bindless slot that has it cached
        std::unordered_map<CacheKey, TextureHandle, CacheKeyHash> m_cache;
        //! Free slot placeholder
        TextureHandle m_placeholder;

        ITextureLoader* m_loader;
        RenderBackend* m_rhi;
        RenderBackendInterface* m_backend;
        GlobalResourceSet* m_globalSet;

        std::vector<Core::UniquePtr<Buffer>> m_usedStagingBuffers;

        //! A textures with loaded raw data and a reserved slot but no GPU resources
        struct PendingUpload {
            TextureHandle handle;
            RawTextureData data;
        };

        std::vector<PendingUpload> m_pendingUploads;
        //! Uploads already submitted, waiting for their bindless slot to be pointed at them
        std::vector<TextureHandle> m_pendingRegister;
    };
}

#endif //SHIFT_TEXTUREMANAGER_HPP
