#include <doctest/doctest.h>

#include <algorithm>
#include <cmath>
#include <optional>
#include <string>

#include "Loaders/ModelLoader/GltfLoader.hpp"
#include "Utility/UtilStandard.hpp"

using Shift::ETextureColorSpace;
using Shift::GltfLoader;
using Shift::MaterialDesc;
using Shift::MeshData;
using Shift::ModelData;
using Shift::NodeDesc;
using Shift::SubmeshDesc;
using Shift::VertexStreams;

//! The asset is Assets/Test/Box.gltf, generated by the script beside it: a 1x1x1 cube split into
//! TWO primitives with a material each, so the merge path (two primitives into one pair of
//! streams, one submesh range each) is exercised rather than assumed. Its four texture URIs name
//! files that do not exist on purpose - nothing in this batch opens them, and the slot's
//! COLORSPACE is the part worth pinning, since loading a normal map as sRGB is the latent bug
//! ADR-0009 section 4 closes.

namespace {
    constexpr uint32_t EXPECTED_VERTICES = 24;
    constexpr uint32_t EXPECTED_INDICES = 36;

    std::string BoxPath() {
        return Shift::Util::GetShiftRoot() + "Assets/Test/Box.gltf";
    }

    std::optional<ModelData> LoadBox() {
        GltfLoader loader;
        return loader.LoadFromFile(BoxPath());
    }
}

TEST_SUITE("GltfLoader") {

TEST_CASE("The cube loads with the shape its asset describes") {
    const std::optional<ModelData> model = LoadBox();
    REQUIRE(model.has_value());

    CHECK(model->sourcePath == BoxPath());
    REQUIRE(model->meshes.size() == 1);
    CHECK(model->materials.size() == 2);
    CHECK(model->nodes.size() == 2);

    const MeshData& mesh = model->meshes[0];
    CHECK(mesh.name == "Box");
    CHECK(mesh.submeshes.size() == 2);
    CHECK(mesh.streams.GetVertexCount() == EXPECTED_VERTICES);
    CHECK(mesh.streams.GetIndexCount() == EXPECTED_INDICES);
    CHECK(mesh.streams.GetTriangleCount() == 12);
}

TEST_CASE("All four streams come out the same length") {
    const std::optional<ModelData> model = LoadBox();
    REQUIRE(model.has_value());
    const VertexStreams& streams = model->meshes[0].streams;

    //! The lockstep invariant, stated as the four sizes rather than through the helper, so a
    //! failure names the stream that drifted. One BufferRangeAllocator range addresses the same
    //! [first, count) in all four merged buffers - that is only meaningful if this holds
    CHECK(streams.positions.size() == EXPECTED_VERTICES);
    CHECK(streams.normals.size() == EXPECTED_VERTICES);
    CHECK(streams.tangents.size() == EXPECTED_VERTICES);
    CHECK(streams.uvs.size() == EXPECTED_VERTICES);
}

TEST_CASE("Submesh ranges tile the index buffer with no gap and no overlap") {
    const std::optional<ModelData> model = LoadBox();
    REQUIRE(model.has_value());
    const MeshData& mesh = model->meshes[0];
    REQUIRE(mesh.submeshes.size() == 2);

    uint32_t expectedFirst = 0;
    for (const SubmeshDesc& submesh : mesh.submeshes) {
        CHECK(submesh.firstIndex == expectedFirst);
        CHECK(submesh.indexCount == 18);
        expectedFirst += submesh.indexCount;
    }
    CHECK(expectedFirst == mesh.streams.GetIndexCount());

    //! Each primitive kept its own material through the merge - the thing that would silently
    //! break if the submesh ranges were assembled in the wrong order
    CHECK(mesh.submeshes[0].materialIndex == 0);
    CHECK(mesh.submeshes[1].materialIndex == 1);
}

TEST_CASE("Every index addresses a real vertex") {
    const std::optional<ModelData> model = LoadBox();
    REQUIRE(model.has_value());
    const VertexStreams& streams = model->meshes[0].streams;

    uint32_t largestIndex = 0;
    for (const uint32_t index : streams.indices) {
        largestIndex = std::max(largestIndex, index);
    }
    //! Mesh-LOCAL indices: the second primitive's values were shifted by the first primitive's
    //! vertex count during the merge. The mesh's own base vertex is not baked in here - it rides
    //! in ObjectData::vertexOffset, because every draw passes vertexOffset = 0
    CHECK(largestIndex == EXPECTED_VERTICES - 1);
    CHECK(largestIndex < streams.GetVertexCount());
}

TEST_CASE("Bounds enclose the geometry they describe") {
    const std::optional<ModelData> model = LoadBox();
    REQUIRE(model.has_value());
    const MeshData& mesh = model->meshes[0];

    for (const glm::vec3& position : mesh.streams.positions) {
        CHECK(mesh.bounds.Contains(position));
        const float distance = glm::length(position - glm::vec3{mesh.bounds.sphere});
        CHECK(distance <= mesh.bounds.sphere.w + 1e-5f);
    }

    //! The unit cube is centred on the origin, so its sphere is the corner distance
    CHECK(mesh.bounds.min.x == doctest::Approx(-0.5f));
    CHECK(mesh.bounds.max.x == doctest::Approx(0.5f));
    CHECK(mesh.bounds.sphere.w == doctest::Approx(std::sqrt(0.75f)));

    //! A submesh covers half the cube, so its box must fit inside the mesh's
    for (const SubmeshDesc& submesh : mesh.submeshes) {
        CHECK(mesh.bounds.Contains(submesh.bounds.min));
        CHECK(mesh.bounds.Contains(submesh.bounds.max));
    }
}

TEST_CASE("Material factors survive the load") {
    const std::optional<ModelData> model = LoadBox();
    REQUIRE(model.has_value());
    REQUIRE(model->materials.size() == 2);

    const MaterialDesc& opaque = model->materials[0];
    CHECK(opaque.name == "BoxMaterialA");
    CHECK(opaque.baseColorFactor.r == doctest::Approx(0.8f));
    CHECK(opaque.baseColorFactor.a == doctest::Approx(1.0f));
    CHECK(opaque.metallicFactor == doctest::Approx(0.25f));
    CHECK(opaque.roughnessFactor == doctest::Approx(0.6f));
    CHECK(opaque.emissiveFactor.r == doctest::Approx(0.1f));
    CHECK_FALSE(opaque.alphaTest);
    CHECK_FALSE(opaque.doubleSided);

    const MaterialDesc& masked = model->materials[1];
    CHECK(masked.name == "BoxMaterialB");
    CHECK(masked.metallicFactor == doctest::Approx(1.0f));
    //! MASK is what selects the alpha-test pipeline variant, so it has to arrive as a flag
    CHECK(masked.alphaTest);
    CHECK(masked.alphaCutoff == doctest::Approx(0.25f));
    CHECK(masked.doubleSided);
}

TEST_CASE("Each texture slot carries the colorspace its MEANING implies") {
    const std::optional<ModelData> model = LoadBox();
    REQUIRE(model.has_value());
    const MaterialDesc& material = model->materials[0];

    CHECK(material.baseColor.id == "box_basecolor.png");
    CHECK(material.normal.id == "box_normal.png");
    CHECK(material.orm.id == "box_orm.png");
    CHECK(material.emissive.id == "box_emissive.png");

    //! Authored colors decode through sRGB; numbers must not. Loading a normal map as sRGB bends
    //! lighting in a way that looks like a BRDF bug rather than a loader bug
    CHECK(material.baseColor.colorSpace == ETextureColorSpace::SRGB);
    CHECK(material.emissive.colorSpace == ETextureColorSpace::SRGB);
    CHECK(material.normal.colorSpace == ETextureColorSpace::Linear);
    CHECK(material.orm.colorSpace == ETextureColorSpace::Linear);

    //! The second material names no textures at all, so every slot must read as unused rather
    //! than as slot 0 of something
    const MaterialDesc& untextured = model->materials[1];
    CHECK_FALSE(untextured.baseColor.IsSet());
    CHECK_FALSE(untextured.normal.IsSet());
}

TEST_CASE("The node hierarchy is flattened parents first") {
    const std::optional<ModelData> model = LoadBox();
    REQUIRE(model.has_value());
    REQUIRE(model->nodes.size() == 2);

    const NodeDesc& root = model->nodes[0];
    CHECK(root.name == "Root");
    CHECK(root.parent == Shift::MODEL_INDEX_NONE);
    CHECK(root.meshIndex == Shift::MODEL_INDEX_NONE);
    CHECK(root.translation.y == doctest::Approx(2.0f));

    const NodeDesc& child = model->nodes[1];
    CHECK(child.name == "BoxNode");
    //! The asset says mesh 1, because mesh 0 is a POINTS primitive the loader drops. So the index
    //! a node carries is an index into ModelData::meshes, NOT the asset's - copying the asset's
    //! through would address a mesh that was never emitted, and with three meshes and only the
    //! middle one dropped it would not even be out of range, just quietly the wrong model
    CHECK(child.meshIndex == 0);
    //! Emitted after its parent, which is what lets a single forward pass compose world
    //! transforms without a stack when the hierarchy container arrives at P4.4
    CHECK(child.parent == 0);
    CHECK(child.scale.x == doctest::Approx(2.0f));
    //! glTF stores quaternions xyzw and glm takes wxyz - a swap here is a silently rotated model
    CHECK(child.rotation.y == doctest::Approx(0.70710678f));
    CHECK(child.rotation.w == doctest::Approx(0.70710678f));
}

TEST_CASE("Authored tangents are passed through, not regenerated") {
    const std::optional<ModelData> model = LoadBox();
    REQUIRE(model.has_value());
    const VertexStreams& streams = model->meshes[0].streams;

    //! Box.gltf ships tangents computed from its own UV layout. Checking them against that layout
    //! proves the loader left them alone: a regenerated or defaulted basis would not line up
    for (size_t i = 0; i < streams.tangents.size(); ++i) {
        const glm::vec3 tangent{streams.tangents[i]};
        CHECK(glm::length(tangent) == doctest::Approx(1.0f).epsilon(1e-3));
        CHECK(glm::dot(tangent, streams.normals[i]) == doctest::Approx(0.0f).epsilon(1e-3));
        CHECK(streams.tangents[i].w == doctest::Approx(-1.0f));
    }
}

TEST_CASE("A file that is not there fails quietly") {
    GltfLoader loader;
    const std::optional<ModelData> missing =
        loader.LoadFromFile(Shift::Util::GetShiftRoot() + "Assets/Test/DoesNotExist.gltf");

    CHECK_FALSE(missing.has_value());
}

}
